import type { Order, Plan } from '@/types/database'

/** Dados fictícios exibidos no modo de demonstração (sem Supabase configurado). */

const daysAgo = (n: number) => new Date(Date.now() - n * 86_400_000).toISOString()
const T = daysAgo(0)

export const DEMO_PLANS: Plan[] = [
  {
    id: 'demo-plano-avulso',
    slug: 'avulso-demo',
    nome_plano: 'Avulso',
    descricao: 'Um álbum sob medida, sem mensalidade.',
    tipo_cobranca: 'avulso',
    preco: 690,
    moeda: 'BRL',
    albuns_inclusos: 1,
    prazo_dias: 10,
    revisoes_inclusas: 2,
    features_json: [],
    destaque: false,
    ativo: true,
    ordem: 1,
    created_at: T,
    updated_at: T,
  },
  {
    id: 'demo-plano-plus',
    slug: 'plus-demo',
    nome_plano: 'Plus',
    descricao: 'Até 5 álbuns por mês com curadoria inclusa.',
    tipo_cobranca: 'assinatura',
    preco: 890,
    moeda: 'BRL',
    albuns_inclusos: 5,
    prazo_dias: 7,
    revisoes_inclusas: 3,
    features_json: [],
    destaque: true,
    ativo: true,
    ordem: 2,
    created_at: T,
    updated_at: T,
  },
]

export const DEMO_ORDERS: Order[] = [
  {
    id: 'demo-pedido-1042',
    numero: 1042,
    client_id: 'demo-user',
    plan_id: 'demo-plano-avulso',
    nome_projeto: 'Casamento Marina & Théo',
    link_fotos_brutas: 'https://drive.google.com/demo-1042',
    estilo_design: 'Clássico',
    briefing: null,
    numero_paginas: 30,
    data_evento: '2026-08-15',
    cliente_final_nome: null,
    cliente_final_telefone: null,
    cliente_final_email: null,
    chave_idempotencia: null,
    fotos_enviadas: 0,
    pago_em: null,
    valor_pago: null,
    stripe_checkout_session_id: null,
    projeto_id: null,
    status: 'aguardando_aprovacao',
    link_aprovacao: 'https://exemplo.com/prova/1042',
    link_entrega_final: null,
    observacoes_admin: null,
    revisoes_usadas: 1,
    prazo_entrega: '2026-09-01',
    finalizado_em: null,
    created_at: daysAgo(6),
    updated_at: daysAgo(1),
  },
  {
    id: 'demo-pedido-1041',
    numero: 1041,
    client_id: 'demo-user',
    plan_id: 'demo-plano-plus',
    nome_projeto: 'Aniversário de 15 anos — Bia',
    link_fotos_brutas: 'https://drive.google.com/demo-1041',
    estilo_design: 'Moderno',
    briefing: null,
    numero_paginas: 24,
    data_evento: '2026-07-02',
    cliente_final_nome: null,
    cliente_final_telefone: null,
    cliente_final_email: null,
    chave_idempotencia: null,
    fotos_enviadas: 0,
    pago_em: null,
    valor_pago: null,
    stripe_checkout_session_id: null,
    projeto_id: null,
    status: 'em_producao',
    link_aprovacao: null,
    link_entrega_final: null,
    observacoes_admin: null,
    revisoes_usadas: 0,
    prazo_entrega: '2026-07-20',
    finalizado_em: null,
    created_at: daysAgo(20),
    updated_at: daysAgo(2),
  },
  {
    id: 'demo-pedido-1038',
    numero: 1038,
    client_id: 'demo-user',
    plan_id: 'demo-plano-avulso',
    nome_projeto: 'Ensaio gestante — Camila',
    link_fotos_brutas: 'https://drive.google.com/demo-1038',
    estilo_design: 'Minimalista',
    briefing: null,
    numero_paginas: 18,
    data_evento: '2026-05-10',
    cliente_final_nome: null,
    cliente_final_telefone: null,
    cliente_final_email: null,
    chave_idempotencia: null,
    fotos_enviadas: 0,
    pago_em: null,
    valor_pago: null,
    stripe_checkout_session_id: null,
    projeto_id: null,
    status: 'finalizado',
    link_aprovacao: null,
    link_entrega_final: 'https://exemplo.com/entrega/1038',
    observacoes_admin: null,
    revisoes_usadas: 2,
    prazo_entrega: '2026-05-28',
    finalizado_em: '2026-05-25',
    created_at: daysAgo(45),
    updated_at: daysAgo(40),
  },
]
