import type {
  AlbumCoverValue,
  AlbumOrientationValue,
  AlbumTypeValue,
  Project,
  VisualOption,
} from '@/types/platform'

const daysAgo = (n: number) => new Date(Date.now() - n * 86_400_000).toISOString()
const daysAhead = (n: number) => new Date(Date.now() + n * 86_400_000).toISOString()

/** Cards visuais do wizard (seção 13) — imagens de referência no lugar de selects simples. */
export const ALBUM_TYPE_OPTIONS: VisualOption<AlbumTypeValue>[] = [
  { value: 'casamento', label: 'Álbum de casamento', description: 'Capa robusta, narrativa completa do dia.', image: 'https://picsum.photos/seed/tipo-casamento/640/480' },
  { value: 'aniversario', label: 'Álbum de aniversário', description: 'Celebração de datas especiais e festas.', image: 'https://picsum.photos/seed/tipo-aniversario/640/480' },
  { value: 'formatura', label: 'Álbum de formatura', description: 'Conquista acadêmica com registro marcante.', image: 'https://picsum.photos/seed/tipo-formatura/640/480' },
  { value: 'premium', label: 'Álbum premium', description: 'Acabamento superior, papel e capa nobres.', image: 'https://picsum.photos/seed/tipo-premium/640/480' },
  { value: 'fotolivro', label: 'Fotolivro', description: 'Formato leve e acessível, ótimo custo-benefício.', image: 'https://picsum.photos/seed/tipo-fotolivro/640/480' },
  { value: 'tradicional', label: 'Álbum tradicional', description: 'O clássico, atemporal, sempre elegante.', image: 'https://picsum.photos/seed/tipo-tradicional/640/480' },
  { value: 'corporativo', label: 'Álbum corporativo', description: 'Eventos institucionais e de empresa.', image: 'https://picsum.photos/seed/tipo-corporativo/640/480' },
]

export const ALBUM_FORMAT_OPTIONS: VisualOption<string>[] = [
  { value: '20x20', label: '20 × 20', description: 'Compacto e versátil.', image: 'https://picsum.photos/seed/album-20x20/640/480' },
  { value: '25x25', label: '25 × 25', description: 'Equilíbrio entre presença e portabilidade.', image: 'https://picsum.photos/seed/album-25x25/640/480' },
  { value: '30x30', label: '30 × 30', description: 'O mais escolhido para celebrações grandes.', image: 'https://picsum.photos/seed/album-30x30/640/480' },
  { value: '30x40', label: '30 × 40', description: 'Mais espaço e impacto por lâmina.', image: 'https://picsum.photos/seed/album-30x40/640/480' },
]

export const ALBUM_ORIENTATION_OPTIONS: VisualOption<AlbumOrientationValue>[] = [
  { value: 'quadrado', label: 'Quadrado', description: 'Formato equilibrado, o mais versátil.', image: 'https://picsum.photos/seed/orientacao-quadrado/480/480' },
  { value: 'horizontal', label: 'Horizontal', description: 'Ideal para paisagens e grupos.', image: 'https://picsum.photos/seed/orientacao-horizontal/640/420' },
  { value: 'vertical', label: 'Vertical', description: 'Destaque para retratos e detalhes.', image: 'https://picsum.photos/seed/orientacao-vertical/420/640' },
]

export const ALBUM_COVER_OPTIONS: VisualOption<AlbumCoverValue>[] = [
  { value: 'fotografica', label: 'Fotográfica', description: 'Capa impressa com a foto de escolha.', image: 'https://picsum.photos/seed/capa-fotografica/640/480' },
  { value: 'tecido', label: 'Tecido', description: 'Textura macia, visual sofisticado.', image: 'https://picsum.photos/seed/capa-tecido/640/480' },
  { value: 'couro', label: 'Couro', description: 'Robustez e elegância clássica.', image: 'https://picsum.photos/seed/capa-couro/640/480' },
  { value: 'acrilico', label: 'Acrílico', description: 'Acabamento moderno e brilhante.', image: 'https://picsum.photos/seed/capa-acrilico/640/480' },
  { value: 'personalizada', label: 'Personalizada', description: 'Sob medida conforme o briefing.', image: 'https://picsum.photos/seed/capa-personalizada/640/480' },
]

function mockPhotos(seedPrefix: string, groups: string[], count: number) {
  return Array.from({ length: count }, (_, i) => ({
    id: `${seedPrefix}-foto-${i + 1}`,
    url: `https://picsum.photos/seed/${seedPrefix}-${i}/480/320`,
    grupo: groups[i % groups.length],
    favorita: i % 4 === 0,
    obrigatoria: i % 7 === 0,
    destaque: i === 0,
    capa: i === 0,
    observacao: i === 0 ? 'Quero esta foto na abertura.' : null,
  }))
}

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'proj-1042',
    numero: 1042,
    nome: 'Casamento Marina & Théo',
    clientId: 'cli-1',
    fotografoId: 'fot-1',
    responsavelId: 'eq-3',
    tipoEvento: 'Casamento',
    dataEvento: daysAgo(35),
    status: 'aguardando_aprovacao_cliente',
    prazo: daysAhead(2),
    dataLimiteProducao: daysAhead(2),
    dataLimiteAprovacao: daysAhead(3),
    createdAt: daysAgo(6),
    metaFotos: 16,
    album: {
      tipo: 'casamento',
      formato: '30x30',
      orientacao: 'quadrado',
      capa: 'tecido',
      quantidadePaginas: 30,
      observacoes: 'Priorizar tons neutros e papel fosco.',
    },
    briefing: {
      nomeEvento: 'Casamento Marina & Théo',
      tipoEvento: 'Casamento',
      data: daysAgo(35),
      local: 'Fazenda Santa Clara, SP',
      quantidadePessoas: '180 convidados',
      estiloDesejado: 'Clássico, elegante, tons neutros',
      preferenciasDiagramacao: 'Uma foto de destaque por página, poucas montagens',
      fotosPrioritarias: 'Entrada da noiva, troca de alianças, primeira dança',
      pessoasQueDevemAparecer: 'Avós dos noivos, padrinhos',
      momentosImportantes: 'Cerimônia ao pôr do sol, discurso do pai da noiva',
      referencias: 'Álbuns @studio.ref no Instagram',
      observacoesGerais: 'Casal pediu revisão rápida — querem o álbum pronto para o aniversário de 1 mês.',
      orientacaoDiagramacao: 'Evitar colagens com mais de 3 fotos por página.',
    },
    photos: mockPhotos('m1042', ['Cerimônia', 'Festa', 'Família', 'Detalhes'], 16),
    designVersions: [
      { id: 'v1', numero: 1, data: daysAgo(3), responsavelId: 'eq-3', arquivo: 'casamento-marina-theo-v1.pdf', comentarios: 'Primeira diagramação enviada.', status: 'enviada' },
      { id: 'v2', numero: 2, data: daysAgo(1), responsavelId: 'eq-3', arquivo: 'casamento-marina-theo-v2.pdf', comentarios: 'Ajustada a ordem das páginas 8-12.', status: 'enviada' },
    ],
    approvals: [
      { id: 'a1', versao: 1, data: daysAgo(2), usuario: 'Marina Alves', status: 'alteracao_solicitada', comentario: 'Trocar a foto de abertura, muito escura.' },
    ],
    activity: [
      { id: 'act1', mensagem: 'Projeto criado a partir do pedido #1042.', data: daysAgo(6) },
      { id: 'act2', mensagem: 'Fotos recebidas (16 imagens).', data: daysAgo(5) },
      { id: 'act3', mensagem: 'Diego Salles iniciou a diagramação.', data: daysAgo(4) },
      { id: 'act4', mensagem: 'Versão 1 enviada para aprovação.', data: daysAgo(3) },
      { id: 'act5', mensagem: 'Marina Alves solicitou alteração na foto de abertura.', data: daysAgo(2) },
      { id: 'act6', mensagem: 'Versão 2 enviada para aprovação.', data: daysAgo(1) },
    ],
  },
  {
    id: 'proj-1041',
    numero: 1041,
    nome: 'Aniversário de 15 anos — Bia',
    clientId: 'cli-2',
    fotografoId: 'fot-1',
    responsavelId: 'eq-4',
    tipoEvento: 'Aniversário',
    dataEvento: daysAgo(20),
    status: 'em_diagramacao',
    prazo: daysAhead(8),
    dataLimiteProducao: daysAhead(8),
    dataLimiteAprovacao: null,
    createdAt: daysAgo(12),
    metaFotos: 10,
    album: {
      tipo: 'aniversario',
      formato: '25x25',
      orientacao: 'quadrado',
      capa: 'acrilico',
      quantidadePaginas: 24,
      observacoes: null,
    },
    briefing: {
      nomeEvento: 'Aniversário de 15 anos — Bianca',
      tipoEvento: 'Aniversário',
      data: daysAgo(20),
      local: 'Espaço Jasmim, Campinas',
      quantidadePessoas: '90 convidados',
      estiloDesejado: 'Moderno, colorido, jovem',
      preferenciasDiagramacao: 'Pode usar montagens e colagens',
      fotosPrioritarias: 'Valsa, troca de sapatinho, making of do vestido',
      pessoasQueDevemAparecer: null,
      momentosImportantes: 'Entrada surpresa, homenagem dos pais',
      referencias: null,
      observacoesGerais: null,
      orientacaoDiagramacao: null,
    },
    photos: mockPhotos('m1041', ['Making of', 'Valsa', 'Festa'], 10),
    designVersions: [
      { id: 'v1', numero: 1, data: daysAgo(2), responsavelId: 'eq-4', arquivo: 'bia-15anos-v1.pdf', comentarios: 'Em produção — primeira versão ainda não enviada.', status: 'em_producao' },
    ],
    approvals: [],
    activity: [
      { id: 'act1', mensagem: 'Projeto criado a partir do pedido #1041.', data: daysAgo(12) },
      { id: 'act2', mensagem: 'Fotos recebidas (10 imagens).', data: daysAgo(9) },
      { id: 'act3', mensagem: 'Paula Nakamura iniciou a diagramação.', data: daysAgo(2) },
    ],
  },
  {
    id: 'proj-1038',
    numero: 1038,
    nome: 'Ensaio gestante — Camila',
    clientId: 'cli-3',
    fotografoId: 'fot-1',
    responsavelId: 'eq-3',
    tipoEvento: 'Ensaio',
    dataEvento: daysAgo(50),
    status: 'finalizado',
    prazo: daysAgo(15),
    dataLimiteProducao: daysAgo(15),
    dataLimiteAprovacao: null,
    createdAt: daysAgo(52),
    metaFotos: 8,
    album: {
      tipo: 'premium',
      formato: '20x20',
      orientacao: 'quadrado',
      capa: 'fotografica',
      quantidadePaginas: 18,
      observacoes: null,
    },
    briefing: {
      nomeEvento: 'Ensaio gestante Camila',
      tipoEvento: 'Ensaio',
      data: daysAgo(50),
      local: 'Estúdio próprio',
      quantidadePessoas: '2 pessoas',
      estiloDesejado: 'Minimalista, clean',
      preferenciasDiagramacao: 'Uma foto por página, muito espaço em branco',
      fotosPrioritarias: null,
      pessoasQueDevemAparecer: null,
      momentosImportantes: null,
      referencias: null,
      observacoesGerais: null,
      orientacaoDiagramacao: null,
    },
    photos: mockPhotos('m1038', ['Estúdio'], 8),
    designVersions: [
      { id: 'v1', numero: 1, data: daysAgo(42), responsavelId: 'eq-3', arquivo: 'camila-gestante-v1.pdf', comentarios: 'Primeira versão.', status: 'enviada' },
      { id: 'v2', numero: 2, data: daysAgo(40), responsavelId: 'eq-3', arquivo: 'camila-gestante-final.pdf', comentarios: 'Aprovada sem ajustes.', status: 'aprovada' },
    ],
    approvals: [
      { id: 'a1', versao: 2, data: daysAgo(39), usuario: 'Camila Torres', status: 'aprovado', comentario: 'Ficou perfeito, obrigada!' },
    ],
    activity: [
      { id: 'act1', mensagem: 'Projeto criado a partir do pedido #1038.', data: daysAgo(52) },
      { id: 'act2', mensagem: 'Projeto aprovado pelo cliente.', data: daysAgo(39) },
      { id: 'act3', mensagem: 'Projeto finalizado e entregue.', data: daysAgo(38) },
    ],
  },
  {
    id: 'proj-1043',
    numero: 1043,
    nome: 'Casamento Fernanda & Lucas',
    clientId: 'cli-4',
    fotografoId: 'fot-2',
    responsavelId: 'eq-4',
    tipoEvento: 'Casamento',
    dataEvento: daysAgo(25),
    status: 'em_revisao_interna',
    prazo: daysAgo(3),
    dataLimiteProducao: daysAgo(3),
    dataLimiteAprovacao: null,
    createdAt: daysAgo(10),
    metaFotos: 12,
    album: {
      tipo: 'casamento',
      formato: '30x40',
      orientacao: 'horizontal',
      capa: 'couro',
      quantidadePaginas: 32,
      observacoes: null,
    },
    briefing: {
      nomeEvento: 'Casamento Fernanda & Lucas',
      tipoEvento: 'Casamento',
      data: daysAgo(25),
      local: 'Sítio Boa Vista, RJ',
      quantidadePessoas: '120 convidados',
      estiloDesejado: 'Romântico, clássico',
      preferenciasDiagramacao: null,
      fotosPrioritarias: 'Cerimônia ao ar livre, festa',
      pessoasQueDevemAparecer: null,
      momentosImportantes: null,
      referencias: null,
      observacoesGerais: 'Cliente já reclamou de atraso em projeto anterior — priorizar prazo.',
      orientacaoDiagramacao: null,
    },
    photos: mockPhotos('m1043', ['Cerimônia', 'Festa'], 12),
    designVersions: [
      { id: 'v1', numero: 1, data: daysAgo(2), responsavelId: 'eq-4', arquivo: 'fernanda-lucas-v1.pdf', comentarios: 'Primeira diagramação, pronta para revisão interna.', status: 'enviada' },
    ],
    approvals: [],
    activity: [
      { id: 'act1', mensagem: 'Projeto criado a partir do pedido #1043.', data: daysAgo(10) },
      { id: 'act2', mensagem: 'Fotos recebidas (12 imagens).', data: daysAgo(8) },
      { id: 'act3', mensagem: 'Paula Nakamura foi atribuída ao projeto.', data: daysAgo(7) },
      { id: 'act4', mensagem: 'Paula Nakamura enviou a versão 1 para revisão interna.', data: daysAgo(2) },
    ],
  },
  {
    id: 'proj-1044',
    numero: 1044,
    nome: 'Ensaio família — Camila Torres',
    clientId: 'cli-3',
    fotografoId: 'fot-1',
    responsavelId: null,
    tipoEvento: 'Ensaio',
    dataEvento: daysAgo(6),
    status: 'pronto_para_diagramacao',
    prazo: daysAhead(10),
    dataLimiteProducao: daysAhead(10),
    dataLimiteAprovacao: null,
    createdAt: daysAgo(6),
    metaFotos: 14,
    album: {
      tipo: 'tradicional',
      formato: '25x25',
      orientacao: 'quadrado',
      capa: 'fotografica',
      quantidadePaginas: 20,
      observacoes: null,
    },
    briefing: {
      nomeEvento: 'Ensaio de família — Camila Torres',
      tipoEvento: 'Ensaio',
      data: daysAgo(6),
      local: 'Parque Ibirapuera, SP',
      quantidadePessoas: '5 pessoas',
      estiloDesejado: 'Natural, leve',
      preferenciasDiagramacao: null,
      fotosPrioritarias: null,
      pessoasQueDevemAparecer: null,
      momentosImportantes: null,
      referencias: null,
      observacoesGerais: null,
      orientacaoDiagramacao: null,
    },
    photos: mockPhotos('m1044', ['Parque'], 14),
    designVersions: [],
    approvals: [],
    activity: [
      { id: 'act1', mensagem: 'Projeto criado a partir do pedido #1044.', data: daysAgo(6) },
      { id: 'act2', mensagem: 'Fotos recebidas (14 imagens).', data: daysAgo(4) },
      { id: 'act3', mensagem: 'Briefing preenchido — pronto para diagramação.', data: daysAgo(3) },
    ],
  },
  {
    id: 'proj-1045',
    numero: 1045,
    nome: 'Aniversário de 1 ano de casados',
    clientId: 'cli-1',
    fotografoId: 'fot-1',
    responsavelId: null,
    tipoEvento: 'Aniversário',
    dataEvento: daysAhead(20),
    status: 'aguardando_fotos',
    prazo: daysAhead(45),
    dataLimiteProducao: daysAhead(45),
    dataLimiteAprovacao: null,
    createdAt: daysAgo(4),
    metaFotos: 30,
    album: {
      tipo: 'aniversario',
      formato: '20x20',
      orientacao: 'quadrado',
      capa: 'fotografica',
      quantidadePaginas: 16,
      observacoes: null,
    },
    briefing: {
      nomeEvento: 'Aniversário de 1 ano de casados — Marina & Théo',
      tipoEvento: 'Aniversário',
      data: daysAhead(20),
      local: 'Casa dos noivos, SP',
      quantidadePessoas: '2 pessoas',
      estiloDesejado: 'Íntimo, romântico',
      preferenciasDiagramacao: null,
      fotosPrioritarias: null,
      pessoasQueDevemAparecer: null,
      momentosImportantes: null,
      referencias: null,
      observacoesGerais: 'Mini álbum surpresa — Théo não pode saber antes da entrega.',
      orientacaoDiagramacao: null,
    },
    photos: mockPhotos('m1045', ['Ensaio em casa'], 20),
    designVersions: [],
    approvals: [],
    activity: [
      { id: 'act1', mensagem: 'Projeto criado a partir do pedido #1045.', data: daysAgo(4) },
      { id: 'act2', mensagem: '20 de 30 fotos enviadas até agora.', data: daysAgo(1) },
    ],
  },
]
