import type { ActivityLogEntry, AlertEntry, Client, Photographer, TeamMember } from '@/types/platform'

/** Dados fictícios da Fase 1 (Clientes, Fotógrafos, Equipe) — só para o admin navegar em modo de demonstração. */

const T = (daysAgo: number) => new Date(Date.now() - daysAgo * 86_400_000).toISOString()

export const MOCK_PHOTOGRAPHERS: Photographer[] = [
  {
    id: 'fot-1',
    nome: 'Rafael Monteiro',
    estudio: 'Estúdio Seu Álbum',
    email: 'contato@seualbum.com.br',
    telefone: '(11) 98472-6702',
    cidade: 'São Paulo',
    projetosCount: 18,
    projetosAtivos: 3,
    clientesCount: 12,
    ultimoAcessoEm: T(0),
    status: 'ativo',
    plano: 'Plus',
    createdAt: T(210),
  },
  {
    id: 'fot-2',
    nome: 'Camila Duarte',
    estudio: 'Duarte Fotografia',
    email: 'camila@duartefotografia.com.br',
    telefone: '(21) 99911-4420',
    cidade: 'Rio de Janeiro',
    projetosCount: 9,
    projetosAtivos: 1,
    clientesCount: 7,
    ultimoAcessoEm: T(2),
    status: 'ativo',
    plano: 'Avulso',
    createdAt: T(140),
  },
  {
    id: 'fot-3',
    nome: 'Bruno Ferraz',
    estudio: 'Ferraz Casamentos',
    email: 'bruno@ferrazcasamentos.com',
    telefone: '(31) 98800-1122',
    cidade: 'Belo Horizonte',
    projetosCount: 4,
    projetosAtivos: 0,
    clientesCount: 4,
    ultimoAcessoEm: T(35),
    status: 'inativo',
    plano: null,
    createdAt: T(90),
  },
]

export const MOCK_CLIENTS: Client[] = [
  {
    id: 'cli-1',
    nome: 'Marina Alves & Théo Costa',
    email: 'marina.alves@gmail.com',
    telefone: '(11) 97711-2233',
    cidade: 'São Paulo',
    estado: 'SP',
    origem: 'Indicação',
    fotografoResponsavelId: 'fot-1',
    projetosCount: 1,
    ultimoProjetoEm: T(4),
    status: 'ativo',
    createdAt: T(30),
    observacoesInternas: 'Pediu revisão rápida — casamento já aconteceu, querem o álbum para o aniversário de 1 mês.',
  },
  {
    id: 'cli-2',
    nome: 'Bianca Ribeiro',
    email: 'bianca.ribeiro15@gmail.com',
    telefone: '(11) 98123-4455',
    cidade: 'Campinas',
    estado: 'SP',
    origem: 'Instagram',
    fotografoResponsavelId: 'fot-1',
    projetosCount: 1,
    ultimoProjetoEm: T(12),
    status: 'ativo',
    createdAt: T(45),
    observacoesInternas: null,
  },
  {
    id: 'cli-3',
    nome: 'Camila Torres',
    email: 'camila.torres@hotmail.com',
    telefone: '(11) 99887-7665',
    cidade: 'São Paulo',
    estado: 'SP',
    origem: 'Site',
    fotografoResponsavelId: 'fot-1',
    projetosCount: 2,
    ultimoProjetoEm: T(6),
    status: 'ativo',
    createdAt: T(130),
    observacoesInternas: null,
  },
  {
    id: 'cli-4',
    nome: 'Fernanda & Lucas Nogueira',
    email: 'fernandanog@gmail.com',
    telefone: '(21) 97744-8899',
    cidade: 'Rio de Janeiro',
    estado: 'RJ',
    origem: 'Indicação',
    fotografoResponsavelId: 'fot-2',
    projetosCount: 1,
    ultimoProjetoEm: T(3),
    status: 'ativo',
    createdAt: T(75),
    observacoesInternas: 'Cliente sensível a prazo — já reclamou de atraso em projeto anterior.',
  },
  {
    id: 'cli-5',
    nome: 'Grupo Ferraz Corporativo',
    email: 'eventos@ferrazcorp.com.br',
    telefone: '(31) 3333-4455',
    cidade: 'Belo Horizonte',
    estado: 'MG',
    origem: 'Indicação',
    fotografoResponsavelId: 'fot-3',
    projetosCount: 0,
    ultimoProjetoEm: null,
    status: 'inativo',
    createdAt: T(88),
    observacoesInternas: null,
  },
]

export const MOCK_TEAM_MEMBERS: TeamMember[] = [
  { id: 'eq-1', nome: 'Rafael Monteiro', email: 'r.monteiro@seualbum.com.br', role: 'admin', status: 'ativo', createdAt: T(300) },
  { id: 'eq-2', nome: 'Juliana Prado', email: 'juliana@seualbum.com.br', role: 'gestor', status: 'ativo', createdAt: T(200) },
  { id: 'eq-3', nome: 'Diego Salles', email: 'diego@seualbum.com.br', role: 'operador', status: 'ativo', createdAt: T(150) },
  { id: 'eq-4', nome: 'Paula Nakamura', email: 'paula@seualbum.com.br', role: 'operador', status: 'ativo', createdAt: T(95) },
]

export const MOCK_ACTIVITY_LOG: ActivityLogEntry[] = [
  { id: 'log-1', mensagem: 'Marina Alves & Théo Costa aprovou a diagramação do álbum.', categoria: 'aprovacao', createdAt: T(1) },
  { id: 'log-2', mensagem: 'Diego Salles iniciou a diagramação do projeto de Bianca Ribeiro.', categoria: 'projeto', createdAt: T(2) },
  { id: 'log-3', mensagem: 'Novo fotógrafo cadastrado: Camila Duarte (Duarte Fotografia).', categoria: 'fotografo', createdAt: T(3) },
  { id: 'log-4', mensagem: 'Fernanda & Lucas Nogueira solicitaram alteração no álbum.', categoria: 'aprovacao', createdAt: T(5) },
  { id: 'log-5', mensagem: 'Novo cliente cadastrado: Camila Torres.', categoria: 'cliente', createdAt: T(8) },
]

export const MOCK_ALERTS: AlertEntry[] = [
  { id: 'alerta-1', mensagem: 'Projeto de Fernanda & Lucas Nogueira está 3 dias atrasado.', severidade: 'urgente' },
  { id: 'alerta-2', mensagem: 'Projeto de Bianca Ribeiro vence em 2 dias.', severidade: 'atencao' },
  { id: 'alerta-3', mensagem: 'Grupo Ferraz Corporativo está inativo há mais de 80 dias.', severidade: 'atencao' },
]
